### ISSUE TITLE
sphere breaks into smaller spheres on collision

### ISSUE THREAD

**Issue by nirajupadhyay11** [wmurphyrd/aframe-physics-extras#11]
Hello,

I am wondering why a dynamic body (a-sphere) breaks into smaller spheres upon collision with another dynamic-body (a-box). Here is a codepen showing this (click to throw the ball) - 

https://codepen.io/nirajupadhyay11/pen/VByQOJ?editors=1011

I have tried increasing the mass of the sphere to stop it from disintegrating but that did not work.

Is there a way to stop this from happening?

Thanks,
Niraj

**Comment by wmurphyrd** [comment]
It's not breaking up, you're just spawning multiple spheres at a time on top of each other. I don't see any of this library in your example. Perhaps you were looking for https://github.com/donmccurdy/aframe-physics-system

**Comment by nirajupadhyay11** [comment]
Thanks Will. You are right I wanted to post the question on aframe-physics-system. Sorry for spamming and thank you for the clue on what is going wrong.
